FROM python:3.12.9-slim

# Set the working directory
WORKDIR /app

ARG DEBIAN_FRONTEND=noninteractive
ARG TZ=Etc/UTC
USER root

# Install dependencies
RUN apt-get update && \
    apt-get upgrade -y &&\
    apt-get install -y --no-install-recommends  \
    sudo \
    wget \
    curl \
    nano \
    htop \
    net-tools \
    iputils-ping \
    psmisc \
    python3-dotenv \
    python3-pip \
    python3-venv \
    python3-dev \
    git \
    procps \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && useradd -ms /bin/bash -u 1000 appuser \
    && echo "appuser:appuser" | chpasswd \
    && chown -R appuser:appuser /app \
    && mkdir -p /data \
    && mkdir -p /data/tools \
    && mkdir -p /data/prompts \
    && mkdir -p /data/resources \
    && chown -R appuser:appuser /data \
    && mkdir -p /var/run/simpletool \
    && chown -R appuser:appuser /var/run/simpletool \
    && mkdir -p /var/run/memcached \
    && chown -R appuser:appuser /var/run/memcached


# Switch to the appuser
USER appuser
WORKDIR /app

# Add ENV
ENV PYTHON_VERSION=3.12
ENV PATH="/home/appuser/.local/bin:${PATH}"

# Copy the current directory contents into the container at /app
COPY src/. /app

# Install Python dependencies
RUN python3 -m pip install --upgrade pip --force-reinstall --break-system-packages \
    && pip install --no-cache-dir -r requirements.txt

# Expose port 8000
EXPOSE 8000
# Run the application
CMD ["bash", "/app/docker-entrypoint.sh"]
